<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <DisableImplicitFSharpCoreReference>true</DisableImplicitFSharpCoreReference>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <OutputPath>..\..\bin\Debug\</OutputPath>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <OutputPath>..\..\bin\Release</OutputPath>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="OrbitModel.fs" />
    <Compile Include="OrbitController.fs" />
    <None Include="paket.references" />
    <Compile Include="Dialogs.fs" />
    <Compile Include="Model.fs" />
	<Compile Include="Image.fs" />
    <Compile Include="App.fs" />
    <Compile Include="Program.fs" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\PRo3D.InstrumentData\PRo3D.InstrumentData.fsproj" />
    <ProjectReference Include="..\PRo3D.InstrumentProjection\PRo3D.InstrumentProjection.fsproj" />
  </ItemGroup>
  <Import Project="..\..\.paket\Paket.Restore.targets" />
</Project>